spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.224.131
    port: 5672
    username: admin
    password: admin  
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
 
 
---
spring:
  profiles: item1
  
server:
  port: 8001
  
eureka:
  instance:
    instance-id: 172.88.3.104:8001
---
spring:
  profiles: item2

server:
  port: 8002
  
  eureka:
  instance:
    instance-id: 172.88.3.104:8002
